### ISSUE TITLE
 FirebaseRemoteConfig.initializeFirebase is not a function

### ISSUE THREAD

**Issue by jmsavani** [capacitor-community/firebase-remote-config#12]
I'm using ionic capacitor for my ionic application. 
When i run application i got the following errors every time 

--------
Code : 

FirebaseRemoteConfig.initializeFirebase(environment.firebase)
FirebaseRemoteConfig.initialize({
		minimumFetchIntervalInSeconds: 3600,
})

------ [
![Screenshot 2020-11-19 at 2 35 49 PM](https://user-images.githubusercontent.com/52349823/99644912-8b811e80-2a74-11eb-8be0-3f8ba19ac372.png)
](url)
[Error] ERROR
Error: Uncaught (in promise): TypeError: FirebaseRemoteConfig.initializeFirebase is not a function. (In 'FirebaseRemoteConfig.initializeFirebase(src_environments_environment__WEBPACK_IMPORTED_MODULE_4__["environment"].firebase)', 'FirebaseRemoteConfig.initializeFirebase' is undefined) capacitor://localhost/main-es2015.js:2581:52 generatorResume@[native code] capacitor://localhost/vendor-es2015.js:175643:75 ZoneAwarePromise@capacitor://localhost/polyfills-es2015.js:4066:41 __awaiter@capacitor://localhost/vendor-es2015.js:175639:36 onInvoke@capacitor://localhost/vendor-es2015.js:90359:39 run@capacitor://localhost/polyfills-es2015.js:3229:53 capacitor://localhost/polyfills-es2015.js:3963:43 onInvokeTask@capacitor://localhost/vendor-es2015.js:90337:43 runTask@capacitor://localhost/polyfills-es2015.js:3273:61 drainMicroTaskQueue@capacitor://localhost/polyfills-es2015.js:3675:46 invokeTask@capacitor://localhost/polyfills-es2015.js:3590:44 timer@capacitor://localhost/polyfills-es2015.js:5658:38
resolvePromise — zone-evergreen.js:798
resolvePromise — zone-evergreen.js:750
(anonymous function) — zone-evergreen.js:860
onInvokeTask — core.js:41632
runTask — zone-evergreen.js:167
drainMicroTaskQueue — zone-evergreen.js:569
invokeTask — zone-evergreen.js:484
timer — zone-evergreen.js:2552
	capacitorConsole (user-script:2:78)
	defaultErrorLogger (vendor-es2015.js:58657)
	handleError (vendor-es2015.js:58710)
	next (vendor-es2015.js:91191)
	(anonymous function) (vendor-es2015.js:86553)
	__tryOrUnsub (vendor-es2015.js:165665)
	next (vendor-es2015.js:165604)
	_next (vendor-es2015.js:165554)
	next (vendor-es2015.js:165531)
	next (vendor-es2015.js:165317)
	emit (vendor-es2015.js:86513)
	run (polyfills-es2015.js:3229)
	onHandleError (vendor-es2015.js:90396)
	runGuarded (polyfills-es2015.js:3242)
	(anonymous function) (polyfills-es2015.js:3776)
	drainMicroTaskQueue (polyfills-es2015.js:3682)
	invokeTask (polyfills-es2015.js:3590)
	timer (polyfills-es2015.js:5658)
------------

[Error] ERROR
Error: Uncaught (in promise): TypeError: FirebaseRemoteConfig. fetchAndActivate is not a function. (In 'FirebaseRemoteConfig. fetchAndActivate(src_environments_environment__WEBPACK_IMPORTED_MODULE_4__["environment"].firebase)', 'FirebaseRemoteConfig. fetchAndActivate' is undefined) capacitor://localhost/main-es2015.js:2581:52 generatorResume@[native code] capacitor://localhost/vendor-es2015.js:175643:75 ZoneAwarePromise@capacitor://localhost/polyfills-es2015.js:4066:41 __awaiter@capacitor://localhost/vendor-es2015.js:175639:36 onInvoke@capacitor://localhost/vendor-es2015.js:90359:39 run@capacitor://localhost/polyfills-es2015.js:3229:53 capacitor://localhost/polyfills-es2015.js:3963:43 onInvokeTask@capacitor://localhost/vendor-es2015.js:90337:43 runTask@capacitor://localhost/polyfills-es2015.js:3273:61 drainMicroTaskQueue@capacitor://localhost/polyfills-es2015.js:3675:46 invokeTask@capacitor://localhost/polyfills-es2015.js:3590:44 timer@capacitor://localhost/polyfills-es2015.js:5658:38
resolvePromise — zone-evergreen.js:798
resolvePromise — zone-evergreen.js:750
(anonymous function) — zone-evergreen.js:860
onInvokeTask — core.js:41632
runTask — zone-evergreen.js:167
drainMicroTaskQueue — zone-evergreen.js:569
invokeTask — zone-evergreen.js:484
timer — zone-evergreen.js:2552
	capacitorConsole (user-script:2:78)
	defaultErrorLogger (vendor-es2015.js:58657)
	handleError (vendor-es2015.js:58710)
	next (vendor-es2015.js:91191)
	(anonymous function) (vendor-es2015.js:86553)
	__tryOrUnsub (vendor-es2015.js:165665)
	next (vendor-es2015.js:165604)
	_next (vendor-es2015.js:165554)
	next (vendor-es2015.js:165531)
	next (vendor-es2015.js:165317)
	emit (vendor-es2015.js:86513)
	run (polyfills-es2015.js:3229)
	onHandleError (vendor-es2015.js:90396)
	runGuarded (polyfills-es2015.js:3242)
	(anonymous function) (polyfills-es2015.js:3776)
	drainMicroTaskQueue (polyfills-es2015.js:3682)
	invokeTask (polyfills-es2015.js:3590)
	timer (polyfills-es2015.js:5658)

**Comment by mic345** [comment]
Hi Jyoti,

I had a similar issue with firebase-analytics, maybe its workaround can be used as a lead - https://github.com/capacitor-community/firebase-analytics/issues/33

mic.

**Comment by jmsavani** [comment]
@mic345 This is not useful for me.
I removed plugin and created function and deploy in firebase and using that i got maintenance config from firebase.
plugin is not useful for my project.
Anyway thank you.
